# stack
type        = "aws-cloudformation"
name        = "nuon-gitea-{{.nuon.install.id}}"
description = "QuickLink to install runner for the gitea app config: Install {{.nuon.install.id}}"

vpc_nested_template_url    = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.2.1/vpc/eks/default/stack.yaml"
runner_nested_template_url = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.2.1/runner/asg/stack.yaml"