type = "deprovision"
name = "{{.nuon.install.id}}-deprovision"
description = "deprovision sandbox and components."
display_name = "deprovision role"
permissions_boundary = "./deprovision_boundary.json"

[[policies]]
managed_policy_name = "AdministratorAccess"